### ISSUE TITLE
Connect frontend to backend auth

### ISSUE THREAD

**Issue by cjlaserna** [CSCI150-LAB01/Meet_in_the_Middle#15]
### To-Do:
- [x] Add a functional logout button
- [x] Look into JWT
- [ ] Account settings page

### Bugs:
XHRPOST [http://localhost:3000/api/user/signup](http://localhost:3000/api/user/signup)
`[HTTP/1.1 500 Internal Server Error 175ms]`
```{
"email":
  "clasernaj@gmail.com",
"password":
  "somePassword!",
"username":
  "clasernaj",
"coordinates":
  [36.8091569,-119.7515704]
}```
